# Generated by Django 4.1.4 on 2022-12-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('tipo', models.CharField(max_length=1000)),
                ('cpf', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('senha', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
